### PR TITLE
Garbage collected javadoc

### PR DESCRIPTION
**Pull request by csviri**

### CODE REVIEW

**Comment by metacosm** [comment]
Why was this closed without merging it?

**Comment by csviri** [comment]
Good question. Will reopen it.

**Comment by csviri** [comment]
Ahh I see, it mas I think added to the main not to next already. So it is already ok on the branches. So closing it again.

**Comment by metacosm** [comment]
Should we delete the branch then?

**Comment by csviri** [comment]
done.

**Pull request closed without merging**
