### PR TITLE
feat: use patch without optimistic locking to remove finalizer

### PR DESCRIPTION
**Pull request by csviri**

### CODE REVIEW

**Comment by csviri** [comment]
@metacosm IMHO this is quite important feature, maybe release 3.1.0 or 3.0.2 with it? WDYT?

**Comment by csviri** [comment]
This PR is replaced by: https://github.com/java-operator-sdk/java-operator-sdk/pull/1249

**Comment by metacosm** [comment]
Should we delete the associated branch if this work is replaced by another PR?

**Comment by csviri** [comment]
yes I guess, will delete this.

**Pull request closed without merging**
