### PR TITLE
Add analytics to website.

### PR DESCRIPTION
**Pull request by amouat**
This PR adds Google Analytics to the website. I think it would be useful to get an idea of how many people are visiting the site. The analytics currently goes to Container Solutions.

This is just a proposal currently, please let me know if there are any concerns or issues.

I've not used the website generator before, so I may have made a mistake in there.

### CODE REVIEW

**Comment by metacosm** [comment]
I don't really know how the site generator works either… but it would be nice if the project admins could easily access the data as well. How do you propose we do that?
If possible, as well, I'd rather use an open-source analytics solution but… 🤷🏼

**Comment by amouat** [comment]
I can add people to the analytics "property" I think. I'm happy to use to open source or community alternative - were you thinking of any in particular?

**Comment by amouat** [comment]
Ah, I think the main issue is we'd need to self host which is a bit of a pain :(

**Comment by metacosm** [comment]
> Ah, I think the main issue is we'd need to self host which is a bit of a pain :(

Indeed… 😢

**Comment by charlottemach** [comment]
LGTM

**Comment by metacosm** [comment]
An interesting open-source alternative with hosted seemingly cheap model: https://plausible.io/

**Pull request merged**
