### PR TITLE
fix: prevent NPE on shutdown if DefaultEventSourceManager.cleanup() is invoked after DefaultEventSourceManeger.close()

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Comment by attilameszaros-form3** [comment]
LGTM

**Comment by attilameszaros-form3** [comment]
LGTM

**Comment by csviri** [comment]
LGTM

**Review by csviri — APPROVED** [review]

**Comment by lburgazzoli** [comment]
@metacosm can this be merged ?

**Review by metacosm — APPROVED** [review]

**Pull request merged**
