### PR TITLE
update Tomcat sample to use EventSources

### PR DESCRIPTION
**Pull request by adam-sandor**
Sample demonstrating multiple Controllers and EventSource on Deployments.

### CODE REVIEW

**Comment by csviri** [comment]
@adam-sandor I'm not convinced we need to put this back, I would keep it in the separate repo. 
@psycho-ir @metacosm  what do you think?

**Comment by adam-sandor** [comment]
I would do the update here, because that's where all the samples are, then move it to where we agree to put them.

**Comment by csviri** [comment]
@adam-sandor but we already moved this to a separate repo. Don't understand why we want to put this back.

**Comment by adam-sandor** [comment]
It was never removed so I'm not really moving it back. I would like to deprecate the tomcat-operator repo.

**Comment by csviri** [comment]
kk, then its fine. 
However let's discuss what samples to keep here in main repo, since are more samples with no clear purpose. We should have clearly defined goal with each of them, since it takes time to maintain them.

**Review by metacosm — APPROVED** [review]
LGTM

**Pull request merged**
