### PR TITLE
fix: fail explicitly if current namespace is requested but not available

### LINKED ISSUE #897: NPE when initializing the operator if there's no explicit namespace set in Kubernetes config

### PR DESCRIPTION
**Pull request by metacosm**
Fixes #897

### CODE REVIEW

**Review by csviri — APPROVED** [review]
LGTM

**Comment by csviri** [comment]
The sonar should not be skipped here.

cc @andreaTP

**Comment by andreaTP** [comment]
@csviri you are right, I messed up the key, it "should" be:

```
github.event.pull_request.head.repo.owner.login
```
instead of:
```
github.event.pull_request.repository_owner
```

here: https://github.com/java-operator-sdk/java-operator-sdk/blob/14403fb1908773afe439835406970c2f1bcf5a0b/.github/workflows/sonar.yml#L18

Do you mind to check?

(ref: https://github.community/t/get-the-head-repository-name-in-prs/17669/2 )

**Comment by csviri** [comment]
> Do you mind to check?

Sure, thx for the hint, will fix it.

**Review by csviri — APPROVED** [review]

**Comment by metacosm** [comment]
Well, it turns out that this "feature" might actually break the Quarkus extension… 😓

**Comment by metacosm** [comment]
Would be nice to set up some sort of CI that would check the quarkus extension for each PR we create it, similarly to what the Quarkus CI does…

**Comment by andreaTP** [comment]
NDR: the Quarkus CI uses the "star" ⭐  action as an hook for running external GH actions

**Comment by metacosm** [comment]
> Well, it turns out that this "feature" might actually break the Quarkus extension… 😓

Actually, it's not breaking so all good. Setting up CI should still be done.

**Pull request merged**
