### PR TITLE
fix: if a watch closes and fails to reconnect, exit the operator

### PR DESCRIPTION
**Pull request by secondsun**
This is one of my proposed fixes for https://github.com/java-operator-sdk/java-operator-sdk/issues/395

### CODE REVIEW

**Comment by secondsun** [comment]
@metacosm The failing test is failing locally  (and it also fails on the main branch). Any thoughts?

**Review by metacosm — COMMENTED** [review]
LGTM

**Review by metacosm — APPROVED** [review]

**Review by adam-sandor — APPROVED** [review]
I think this is a good solution for a rare event. I like that the framework gets tested on some buggy clusters so we can get these edge cases handled.

**Comment by metacosm** [comment]
Going ahead with the merge despite the tests failing. I've checked the PR locally on my system and everything works fine. Not sure why the tests are failing all the sudden.

**Comment by secondsun** [comment]
The tests also passed before the rebase so they work sometime!

**Pull request merged**
