### PR TITLE
refactor: make AbstractConfigurationService easier to use by sub-classes

### PR DESCRIPTION
**Pull request by metacosm**

### CODE REVIEW

**Comment by adam-sandor** [comment]
I'm again missing the explanation for the motivation behind the change.

**Comment by metacosm** [comment]
@adam-sandor it's all in the title 😄 `AsbtractConfigurationService` is an abstract class meant to be extended but as it is, it's not very usable by subclasses because it really doesn't provide ways to interact with its internal structure.

**Comment by metacosm** [comment]
@adam-sandor I'm going to go ahead and merge these changes as I need them for the quarkus extension.

**Comment by adam-sandor** [comment]
sure, go for it :) but do know that I hate abstract classes 😂

**Comment by metacosm** [comment]
Well, the class is not new, I just made it easier to use downstream… and yes, abstract classes certainly have their flaws. 😄

**Pull request merged**
