### PR TITLE
feat: retry and retry configuration decoupling

### PR DESCRIPTION
**Pull request by csviri**

### CODE REVIEW

**Review by metacosm — APPROVED** [review]
LGTM but this is a breaking change so we have to figure out when / how to introduce it…

**Comment by csviri** [comment]
To be honest, I think we should define what API's we cover under semver, (this might be one). But because of this would not introduce a next major version for sure. So would stick with 3.1 tbh.

**Comment by csviri** [comment]
Will try to make it backwards compatible and deprecate the old previous API

**Comment by csviri** [comment]
Will try to make it backwards compatible, and deprecate the old API. Then remove it in v4.

**Comment by metacosm** [comment]
I'm fine with sticking with 3.1 if it's too much trouble… Or this could wait for some later time… 🤷🏼 😀

**Pull request merged**
