### PR TITLE
feat: demonstrate contract-first CRDs

### PR DESCRIPTION
**Pull request by derlin**
Modify the leader-election sample to use contract-first. That is, the CRDs is written in YAML and the java code is generated automatically using the java-generator-maven-plugin from fabric8.

#1338

### CODE REVIEW

**Review by csviri — COMMENTED** [review]
thanks @derlin , the tests are failing it seems that the CRD is not applied, could you take a look pls?

**Comment by derlin** [comment]
I missed lots of details, sorry for that. Should be fixed now !

**Review by csviri — APPROVED** [review]
LGTM

**Review by metacosm — APPROVED** [review]
LGTM, thank you!

**Comment by derlin** [comment]
Great thanks! May I kindly ask to add the label hacktoberfest-accepted to it?

**Pull request merged**
