### PR TITLE
Don't install a shutdown hook by default

### LINKED ISSUE #434: Don't install a shutdown hook by default
When the Operator class is instantiated, it automatically registers a shutdown hook:

```java
Runtime.getRuntime().addShutdownHook(new Thread(this::close))
```

As the startup of the operator is responsibility of the operator developer, I think the shutdown should be left to the user otherwise there may be some conflict and undefined behavior because there may be the need to perform some logic before the operator shuts down.

I'm proposing to make this behavior explicit, like

```java
operator.installShutdownHook();
```

### PR DESCRIPTION
**Pull request by lburgazzoli**
Fixes #434

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@metacosm the failure here seems not related to he PR.

**Comment by metacosm** [comment]
I'd rather keep the current behavior as the default so that `close` is automatically called when the operator is shut down. However, we could indeed have an `installShutdownHook` method on `Operator` that would take a lambda as parameter and wrap it so that `close` would also be called after whatever user logic needs to happen first.

**Comment by lburgazzoli** [comment]
I wonder if that's correct, as example in quarkus, the k8s client is closed as part of the [lifecycle](https://github.com/quarkusio/quarkus/blob/main/extensions/kubernetes-client/runtime/src/main/java/io/quarkus/kubernetes/client/runtime/KubernetesClientProducer.java#L25-L30)  so I'm not sure if explicitly add something to the shutdown hook, may cause to invoke an operation on an already closed/disposed resource

**Comment by metacosm** [comment]
On second thought, it makes sense to move ahead with this change, in particular so that frameworks can decide how to deal with stopping the operator in an idiomatic way. @lburgazzoli can you give me write access to your branch so that I can push updates before merging?

**Comment by lburgazzoli** [comment]
@metacosm sent an invitation

**Comment by metacosm** [comment]
Hmm, seems like I still can't push:  `! [remote rejected]   gh-434 -> gh-434 (refusing to allow an OAuth App to create or update workflow `.github/workflows/master-snapshot-release.yml` without `workflow` scope)`
I guess I need to do a proper fork as opposed to one from my IDE :)

**Comment by lburgazzoli** [comment]
> Hmm, seems like I still can't push: `! [remote rejected] gh-434 -> gh-434 (refusing to allow an OAuth App to create or update workflow `.github/workflows/master-snapshot-release.yml`without`workflow` scope)`
> I guess I need to do a proper fork as opposed to one from my IDE :)

Since it is quite a small change, feel free to create a new PR, I really don't mind :)

**Comment by metacosm** [comment]
Replaced by #498

**Pull request closed without merging**
