### PR TITLE
fix: properly index otherwise ignored dependency

### LINKED ISSUE #272: Registering EventSource fails in Quarkus project
Looks like trying to register an EventSource in a Quarkus-powered operator results in this error. See https://github.com/java-operator-sdk/memcached-operator-sample

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------< io.javaoperatorsdk:memcached-operator >----------------
[INFO] Building Operator SDK - Samples - Memcached 0.1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- quarkus-maven-plugin:1.10.5.Final:dev (default-cli) @ memcached-operator ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 7 source files to C:\Users\adams\IdeaProjects\memcached-operator\target\classes
Listening for transport dt_socket at address: 5005
2020-12-25 18:04:40,646 INFO  [org.jbo.threads] (main) JBoss Threads version 3.1.1.Final
2020-12-25 18:04:41,093 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.kubernetes.client.deployment.KubernetesClientProcessor#process threw an exception: java.lang.IllegalArgumentException: Class io.javaoperatorsdk.operator.processing.event.AbstractEventSource was not found in the index
	at io.quarkus.deployment.util.JandexUtil.fetchFromIndex(JandexUtil.java:263)
	at io.quarkus.deployment.util.JandexUtil.findParametersRecursively(JandexUtil.java:113)
	at io.quarkus.deployment.util.JandexUtil.findParametersRecursively(JandexUtil.java:126)
	at io.quarkus.deployment.util.JandexUtil.resolveTypeParameters(JandexUtil.java:71)
	at io.quarkus.kubernetes.client.deployment.KubernetesClientProcessor.lambda$findWatchedClasses$11(KubernetesClientProcessor.java:145)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.quarkus.kubernetes.client.deployment.KubernetesClientProcessor.findWatchedClasses(KubernetesClientProcessor.java:143)
	at io.quarkus.kubernetes.client.deployment.KubernetesClientProcessor.process(KubernetesClientProcessor.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:832)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:254)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:135)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:55)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:75)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:361)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:52)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:129)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:82)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:144)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.kubernetes.client.deployment.KubernetesClientProcessor#process threw an exception: java.lang.IllegalArgumentException: Class io.javaoperatorsdk.operator.processing.event.AbstractEventSource was not found in the index
	at io.quarkus.deployment.util.JandexUtil.fetchFromIndex(JandexUtil.java:263)
	at io.quarkus.deployment.util.JandexUtil.findParametersRecursively(JandexUtil.java:113)
	at io.quarkus.deployment.util.JandexUtil.findParametersRecursively(JandexUtil.java:126)
	at io.quarkus.deployment.util.JandexUtil.resolveTypeParameters(JandexUtil.java:71)
	at io.quarkus.kubernetes.client.deployment.KubernetesClientProcessor.lambda$findWatchedClasses$11(KubernetesClientProcessor.java:145)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.quarkus.kubernetes.client.deployment.KubernetesClientProcessor.findWatchedClasses(KubernetesClientProcessor.java:143)
	at io.quarkus.kubernetes.client.deployment.KubernetesClientProcessor.process(KubernetesClientProcessor.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:832)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)

	at io.quarkus.builder.Execution.run(Execution.java:116)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:148)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:252)
	... 9 more
Caused by: java.lang.IllegalArgumentException: Class io.javaoperatorsdk.operator.processing.event.AbstractEventSource was not found in the index
	at io.quarkus.deployment.util.JandexUtil.fetchFromIndex(JandexUtil.java:263)
	at io.quarkus.deployment.util.JandexUtil.findParametersRecursively(JandexUtil.java:113)
	at io.quarkus.deployment.util.JandexUtil.findParametersRecursively(JandexUtil.java:126)
	at io.quarkus.deployment.util.JandexUtil.resolveTypeParameters(JandexUtil.java:71)
	at io.quarkus.kubernetes.client.deployment.KubernetesClientProcessor.lambda$findWatchedClasses$11(KubernetesClientProcessor.java:145)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.quarkus.kubernetes.client.deployment.KubernetesClientProcessor.findWatchedClasses(KubernetesClientProcessor.java:143)
	at io.quarkus.kubernetes.client.deployment.KubernetesClientProcessor.process(KubernetesClientProcessor.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:832)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)

2020-12-25 18:04:41,093 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure

```

### PR DESCRIPTION
**Pull request by metacosm**
Fixes #272. The core framework dependency needs to be a runtime
dependency so that it gets put in the extension-using application. We
also need to index the dependency explicitly because Quarkus doesn't do
it automatically (as things might get unruly fast).

### CODE REVIEW

**Comment by psycho-ir** [comment]
Can we have a test, either unit test or integration test for this fix? to ensure the same issue wouldn't happen again later on.

**Comment by metacosm** [comment]
> Can we have a test, either unit test or integration test for this fix? to ensure the same issue wouldn't happen again later on.

Yes, definitely.

**Comment by psycho-ir** [comment]
> > Can we have a test, either unit test or integration test for this fix? to ensure the same issue wouldn't happen again later on.
> 
> Yes, definitely.

Thanks

**Comment by metacosm** [comment]
Ready for merge.

**Comment by adam-sandor** [comment]
LGTM

**Pull request merged**
