### PR TITLE
improve: filters accept super types

### PR DESCRIPTION
**Pull request by csviri**

### CODE REVIEW

**Comment by csviri** [comment]
cc @shawkins

**Comment by shawkins** [comment]
LGTM, thanks @csviri

**Comment by metacosm** [comment]
Wondering if this has an impact on backwards compatibility.

**Comment by csviri** [comment]
Probably not, I guess most of the users use just the target resources. Might be more correct to target `next` version probably

**Comment by shawkins** [comment]
> Wondering if this has an impact on backwards compatibility.

There should not be, this is widening, not narrowing what is accepted.  Are you worried about exotic scenarios such as users using reflection to find these methods?

**Comment by csviri** [comment]
(changed it to target `next` )

**Comment by metacosm** [comment]
> > Wondering if this has an impact on backwards compatibility.
> 
> There should not be, this is widening, not narrowing what is accepted. Are you worried about exotic scenarios such as users using reflection to find these methods?

You're right, my concern was unwarranted.

**Review by metacosm — APPROVED** [review]

**Pull request merged**
