### PR TITLE
fix: remove problematic leader election unit test

### PR DESCRIPTION
**Pull request by csviri**
this test would fail for anyone that has kube config inited locally that makes is quite problematic, would rather remove it

### CODE REVIEW

**Comment by csviri** [comment]
cc @honnix

**Comment by honnix** [comment]
OK I see, so it would fail if kubeconfig does have `namespace` set.

**Comment by csviri** [comment]
> OK I see, so it would fail if kubeconfig does have `namespace` set.

yep, checking how to unset it, but did not found anything smart to do that :(

**Comment by honnix** [comment]
Let's kill it then. It's not worth. :)

**Review by honnix — APPROVED** [review]

**Review by metacosm — APPROVED** [review]

**Pull request merged**
