### PR TITLE
docs: workflows

### PR DESCRIPTION
**Pull request by csviri**

### CODE REVIEW

**Comment by mstatv** [comment]
@csviri just wanted to confirm the below happened before pulling in CI changes that were merged to main earlier?  

> Kudos, SonarCloud Quality Gate passed!    [Quality Gate passed](https://sonarcloud.io/dashboard?id=java-operator-sdk_java-operator-sdk&pullRequest=1274)
> 
> [Bug](https://sonarcloud.io/project/issues?id=java-operator-sdk_java-operator-sdk&pullRequest=1274&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=java-operator-sdk_java-operator-sdk&pullRequest=1274&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=java-operator-sdk_java-operator-sdk&pullRequest=1274&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=java-operator-sdk_java-operator-sdk&pullRequest=1274&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=java-operator-sdk_java-operator-sdk&pullRequest=1274&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=java-operator-sdk_java-operator-sdk&pullRequest=1274&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=java-operator-sdk_java-operator-sdk&pullRequest=1274&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=java-operator-sdk_java-operator-sdk&pullRequest=1274&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=java-operator-sdk_java-operator-sdk&pullRequest=1274&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=java-operator-sdk_java-operator-sdk&pullRequest=1274&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=java-operator-sdk_java-operator-sdk&pullRequest=1274&resolved=false&types=CODE_SMELL) [15 Code Smells](https://sonarcloud.io/project/issues?id=java-operator-sdk_java-operator-sdk&pullRequest=1274&resolved=false&types=CODE_SMELL)
> 
> [](https://sonarcloud.io/component_measures?id=java-operator-sdk_java-operator-sdk&pullRequest=1274&metric=new_coverage&view=list) [58.2% Coverage](https://sonarcloud.io/component_measures?id=java-operator-sdk_java-operator-sdk&pullRequest=1274&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=java-operator-sdk_java-operator-sdk&pullRequest=1274&metric=new_duplicated_lines_density&view=list) [0.7% Duplication](https://sonarcloud.io/component_measures?id=java-operator-sdk_java-operator-sdk&pullRequest=1274&metric=new_duplicated_lines_density&view=list)

**Comment by csviri** [comment]
I think yes, it is not running for the latest commit. So everything seems to be ok. Thx @mstatv

**Comment by mstatv** [comment]
@csviri :+1:  awesome - just saw this and wanted to confirm thanks for the quick response

**Review by metacosm — APPROVED** [review]
Let's merge it!

**Pull request merged**
