### PR TITLE
Minor fix: optimize var usage

### PR DESCRIPTION
**Pull request by zuston**

### CODE REVIEW

**Comment by csviri** [comment]
thx @zuston !

TBH, this sample needs a quite big refactor/redisign, will do it probably soon.

**Comment by zuston** [comment]
Thanks for your great work on this project. 

Got it. I'll close it. Right? @csviri

**Review by csviri — APPROVED** [review]

**Comment by csviri** [comment]
> Thanks for your great work on this project.
> 
> Got it. I'll close it. Right? @csviri

thx! yes, pls

**Comment by csviri** [comment]
Merged it, for now, thx!

**Pull request merged**
