### PR TITLE
chore: fabric8 client 6.4

### PR DESCRIPTION
**Pull request by csviri**

### CODE REVIEW

**Comment by csviri** [comment]
@metacosm I think we can merge this now, since the client is already in quarkus.

**Comment by metacosm** [comment]
> @metacosm I think we can merge this now, since the client is already in quarkus.

Only in `main`, though. I'm OK merging it with the understanding that it'll be more difficult to release a new version if we also need that version to be used in Quarkus…

**Comment by csviri** [comment]
kk, let's wait until quarkus released.

**Comment by metacosm** [comment]
I think we should merge this now to target Quarkus 3.

**Review by metacosm — APPROVED** [review]

**Pull request merged**
