### PR TITLE
Tweet on release!

### PR DESCRIPTION
**Pull request by RishiKumarRay**
#905

### CODE REVIEW

**Comment by csviri** [comment]
@RishiKumarRay  we already have a relase workflow, I think this should be added rather as a next action after the release is done. So we tweet only if the release not failed. Take a look here:
https://github.com/java-operator-sdk/java-operator-sdk/blob/d38d694e1a7775e1374b8e71c136dd4cb6002283/.github/workflows/release.yml#L28

**Comment by RishiKumarRay** [comment]
on:
  release:
    types: [Release Maven package]
@csviri you mean this ?

**Comment by RishiKumarRay** [comment]
@csviri can you check now hope i have done in right way now

**Comment by csviri** [comment]
> @csviri can you check now hope i have done in right way now

thx, better just this is the ` update-working-version`  job, what happens parallel to the `publish`, so if you could move it to the last step to `publish` that would be perfect.

**Comment by RishiKumarRay** [comment]
@csviri  move to line number 15 in release.yml? am i right ?

**Comment by csviri** [comment]
> @csviri move to line number 15 in release.yml? am i right ?

to line 36.

**Comment by RishiKumarRay** [comment]
@csviri oh yes , thanks i have updated this please review

**Review by csviri — APPROVED** [review]
LGTM

**Comment by csviri** [comment]
will manage the account then merge, thx! @RishiKumarRay

**Comment by RishiKumarRay** [comment]
Yeah sure @csviri  thanks

**Comment by metacosm** [comment]
Woot! Thank you. 🎉

**Pull request merged**
