### PR TITLE
docs: slack badge

### PR DESCRIPTION
**Pull request by csviri**

### CODE REVIEW

**Comment by andreaTP** [comment]
How does it work to obtain an account to join?

**Comment by csviri** [comment]
Hmm, this is Kubernetes Slack, yeah that should be somehow described there. It is below, but a join link would be helpful.

**Comment by csviri** [comment]
if you already there it will just open the app / website.

**Comment by csviri** [comment]
will check if i can ad a tooltip or something, little later.

**Comment by csviri** [comment]
added tooltip with invite link. We might add a :grey_question: mark with tooltip also, but this might be enough.

**Pull request merged**
